#!/usr/bin/env python3
"""
Render a compact audit report comparing current engine labels against
manual-review labels across the full corpus.

This is a reporting layer on top of `manual_review_compare.py`: it turns the
current comparison state into a scan-friendly markdown table so batch spot
checks can be reviewed quickly after each corpus run.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_json(path: str | Path) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_jsonl(path: str | Path) -> list[dict]:
    rows = []
    for raw in Path(path).read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        rows.append(json.loads(raw))
    return rows


def render_markdown(diff: dict, *, title: str = "Manual Review Audit") -> str:
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- packet rows: `{diff.get('packet_rows', 0)}`")
    lines.append(f"- manual rows: `{diff.get('manual_rows', 0)}`")
    lines.append(f"- missing manual reviews: `{len(diff.get('missing_manual_reviews') or [])}`")
    lines.append(f"- mismatch kinds: `{diff.get('mismatch_kind_counts') or {}}`")
    lines.append("")
    acc = diff.get("field_accuracy") or {}
    lines.append("| Field | Accuracy | Correct / Total |")
    lines.append("|---|---:|---:|")
    for field in (
        "has_rootfs",
        "has_web_ui",
        "artifact_kind",
        "probe_readiness",
        "blob_family",
        "encrypted_container",
        "best_next_action",
        "top_risk_family",
    ):
        stat = acc.get(field) or {}
        lines.append(
            f"| `{field}` | `{stat.get('accuracy', 0):.4f}` | `{stat.get('correct', 0)} / {stat.get('total', 0)}` |"
        )

    lines.append("")
    lines.append("## Per Input")
    lines.append("")
    lines.append("| Review ID | Vendor | Model | Engine Risk | Manual Risk | Action | Status |")
    lines.append("|---|---|---|---|---|---|---|")
    for row in diff.get("per_review") or []:
        fw = row.get("firmware") or {}
        eng = row.get("engine_labels") or {}
        man = row.get("manual_labels") or {}
        status = "MATCH" if not (row.get("mismatches") or []) else "MISMATCH"
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{row.get('review_id', '')}`",
                    fw.get("vendor", ""),
                    fw.get("model", ""),
                    f"`{eng.get('top_risk_family', '')}`",
                    f"`{man.get('top_risk_family', '')}`",
                    f"`{man.get('best_next_action', '')}`",
                    f"`{status}`",
                ]
            )
            + " |"
        )

    missing = diff.get("missing_manual_reviews") or []
    if missing:
        lines.append("")
        lines.append("## Missing Manual Reviews")
        lines.append("")
        for review_id in missing:
            lines.append(f"- `{review_id}`")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Render a markdown audit from manual_review_compare output.")
    ap.add_argument("--diff", required=True, help="Path to JSON diff generated by manual_review_compare.py")
    ap.add_argument("--markdown-out", required=True, help="Where to write the audit markdown")
    ap.add_argument("--title", default="Manual Review Audit", help="Markdown report title")
    args = ap.parse_args()

    diff = load_json(args.diff)
    md = render_markdown(diff, title=args.title)
    Path(args.markdown_out).write_text(md, encoding="utf-8")
    print(json.dumps({"markdown_out": args.markdown_out, "packet_rows": diff.get("packet_rows"), "manual_rows": diff.get("manual_rows")}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
